### ISSUE TITLE
Make syntax highlighting more complete, and support Svelte 5

### ISSUE THREAD

**Issue by didier** [zed-extensions/svelte#1] opened 2024-07-11 13:38 UTC
With Svelte 5 around the corner, now would be a good time to update the Svelte extension to be compatible with it, alongside some other syntax highlighting that's still definitely missing when compared to VS Code:
https://github.com/zed-industries/zed/issues/12833

**Comment by savetheclocktower** [comment] 2024-09-05 23:32
I'm going to use this issue to lobby for a switch to [the `tree-sitter-grammars` version of `tree-sitter-svelte`](https://github.com/tree-sitter-grammars/tree-sitter-svelte). I'm not a Zed user, but I think I've caused them some recent pain, so perhaps I can atone.

Earlier this year, I saw that `tree-sitter-svelte` hadn't yet been updated to support the stuff being teased in the [Svelte 5 preview](https://svelte-5-preview.vercel.app/docs/introduction), so I made a few PRs to [himujjai/tree-sitter-svelte](https://github.com/Himujjal/tree-sitter-svelte/). They all sat open for a while, but @amaanq noticed them at a time when a lot of work was happening in the `tree-sitter-grammars` organization, and took some time to create his own `tree-sitter-svelte` parser. That parser was clearly based on @Himujjal’s, but incorporated the PRs I'd submitted alongside other logic and naming overhauls. It had support for `#snippet` and `@render` from the get-go. But it didn't yet have a corpus; I figured @amaanq would adapt the one that already existed, but I suppose it fell through the cracks during a busy time.

I had occasion to dip back into Svelte a couple months ago and ended up opening [a much larger PR](https://github.com/tree-sitter-grammars/tree-sitter-svelte/pull/5) against that new repo that I hope will be a big leap forward. Despite not having had its own local corpus, the `tree-sitter-grammars` repo has a CI job that runs on PRs; it tests the parser against a large corpus of data from the Svelte repo itself. This inspired me to track down the test cases that were still failing. At this point, I believe that that PR supports everything that Svelte itself supports — or at least everything it's got test cases for.

I didn't know that Zed was using `himujjai/tree-sitter-svelte`. Eventually, my PRs for that original repo got some attention; but I'm still hoping the community can switch over to the `tree-sitter-grammars` org's parser. Once [that PR](https://github.com/tree-sitter-grammars/tree-sitter-svelte/pull/5) lands (any feedback from Svelte users would be appreciated!) I think it'll go long a way toward solving [zed/12833](https://github.com/zed-industries/zed/issues/12833).

I'm here because I've been made aware [that one of my `himujjai/tree-sitter-svelte` PRs](https://github.com/Himujjal/tree-sitter-svelte/pull/50) caused a regression in `#each` blocks… but I believe this issue may not be present on `himujjai/tree-sitter-svelte`’s `main` branch, and almost certainly isn't present [in my PR here](https://github.com/tree-sitter-grammars/tree-sitter-svelte/pull/5). I'll probably still work on a fix for `himujjai/tree-sitter-svelte` just to reduce the harm in the short term, but otherwise I'd rather spend my energy on improving the quality of `tree-sitter-grammars/tree-sitter-svelte`.

I think it'd be good to get folks to standardize on repos that are owned by the `tree-sitter-grammars` org — the CI hygiene alone is a big deal! — because I think it makes those parsers feel less “orphaned.” Even if the same people end up contributing to the repo!

In this case, to switch over wouldn't be a quick task, since a lot of nodes got renamed, but I'd be happy to help.

**Comment by Himujjal** [comment] 2024-09-05 23:34
@savetheclocktower please feel free to use the grammar repo. i can give you full access

**Comment by AlbertMarashi** [comment] 2024-09-07 02:54
@savetheclocktower I was actually attempting to implement/rewrite [Himujjal/tree-sitter-svelte](Himujjal/tree-sitter-svelte) because I quite a few implementation flaws with it.

I'm glad to see that there is another tree-sitter for Svelte, after reviewing the code, it seems a lot more higher quality.

I will review it further, but so far it's a +1 on my side

**Comment by AlbertMarashi** [comment] 2024-09-07 04:02
@savetheclocktower what do you suggest here?

It seems like you're making commits to both, but I think its important to centralize efforts into a single repository, and archive the other.

I'd like to move forward on a decision here rather quickly because I'd like to fix a lot of these issues as soon as possible, and start closing some other issues that exist around svelte.

**Comment by savetheclocktower** [comment] 2024-09-07 04:09
> It seems like you're making commits to both, but I think its important to centralize efforts into a single repository, and archive the other.

The extent of my contribution to `himujjai/tree-sitter-svelte` is to fix the regression that my previous PR caused. I do not plan to make any other commits to that repo. I don't use Zed and am only an occasional user of Svelte, but my goal here was to make the maintainers of this extension aware of the newer `tree-sitter-svelte` repo.

As far as I'm concerned, that's the one that people should be moving toward. I'm not going to use my new commit bit on `himujjai/tree-sitter-svelte` to tell people not to use it — feels a bit gauche! — but if Zed migrates then that's a victory.

**Comment by AlbertMarashi** [comment] 2024-09-07 04:14
I shall push it forward then, leave it with me

**Closed** 2024-09-17 16:02 UTC
